In [1]:
import pandas as pd

## Prepare for Raw Variables

### Sptial units

In [2]:
#read in 2011 MSOA and the corresponding Local Authority & Region for Southwest England (SW) and London
msoa_sw_2011 = pd.read_csv('data00/msoa_sw_2011.csv')
msoa_london_2011 = pd.read_csv('data00/msoa_london_2011.csv')

In [3]:
msoa_sw_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MSOA11CD  229 non-null    object
 1   MSOA11NM  229 non-null    object
 2   LAD11CD   229 non-null    object
 3   LAD11NM   229 non-null    object
 4   RGN11CD   229 non-null    object
 5   RGN11NM   229 non-null    object
dtypes: object(6)
memory usage: 10.9+ KB

In [4]:
msoa_london_2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 983 entries, 0 to 982
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MSOA11CD  983 non-null    object
 1   MSOA11NM  983 non-null    object
 2   LAD11CD   983 non-null    object
 3   LAD11NM   983 non-null    object
 4   RGN11CD   983 non-null    object
 5   RGN11NM   983 non-null    object
dtypes: object(6)
memory usage: 46.2+ KB

In [5]:
#read in the lookup sheet between 2001 MSOA and 2011 MSOA
mosa_01to11=pd.read_csv('data00/MSOA_2001_to_2011.csv')

In [6]:
#add the corresponding 2001 MSOA for SW and London
sw0 = msoa_sw_2011.merge(mosa_01to11, on='MSOA11CD', how='left')
london0 = msoa_london_2011.merge(mosa_01to11, on='MSOA11CD', how='left')

In [7]:
sw0.isnull().values.any()

False

In [8]:
london0.isnull().values.any()

True

In [9]:
london0[london0.isna().any(axis=1)]

,MSOA11CD,MSOA11NM,LAD11CD,LAD11NM,RGN11CD,RGN11NM,MSOA01CD,MSOA01NM,CHGIND
959,E02006928,Greenwich 035,E09000011,Greenwich,E12000007,London,NaN,NaN,NaN

In [10]:
london0 = london0.drop(labels=959, axis=0)
london0 = london0.reset_index(drop=True)

In [11]:
london0.isnull().values.any()

False

In [12]:
sw0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 230 entries, 0 to 229
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MSOA11CD  230 non-null    object
 1   MSOA11NM  230 non-null    object
 2   LAD11CD   230 non-null    object
 3   LAD11NM   230 non-null    object
 4   RGN11CD   230 non-null    object
 5   RGN11NM   230 non-null    object
 6   MSOA01CD  230 non-null    object
 7   MSOA01NM  230 non-null    object
 8   CHGIND    230 non-null    object
dtypes: object(9)
memory usage: 18.0+ KB

In [13]:
london0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MSOA11CD  986 non-null    object
 1   MSOA11NM  986 non-null    object
 2   LAD11CD   986 non-null    object
 3   LAD11NM   986 non-null    object
 4   RGN11CD   986 non-null    object
 5   RGN11NM   986 non-null    object
 6   MSOA01CD  986 non-null    object
 7   MSOA01NM  986 non-null    object
 8   CHGIND    986 non-null    object
dtypes: object(9)
memory usage: 69.5+ KB

In [14]:
sw0.groupby(['CHGIND']).size()

CHGIND
M      2
U    228
dtype: int64

In [15]:
london0.groupby(['CHGIND']).size()

CHGIND
M      8
S      6
U    951
X     21
dtype: int64

Please notice the change in the number of rows after merging. The reason is that some 2001 MSOAs are merged into one in 2011 MSOA and some 2001 MSOAs are split into two into 2011 MSOAs. In column 'CHGIND', M means several 2001 MSOAs are merged into one 2011 MSOA; S means one 2001 MSOA are split into several 2011 MSOAs. Since the analysis will be made based on 2011 MSOA, only the rows whose 'CHGIND' value is M should take special care of. To facilitate the data processing process, I decided to first combine the sw and london dataset.

In [16]:
#combine sw and london dataset into one to facilitate the data processing.
swandlondon0 = pd.concat([sw0, london0],ignore_index=True)

In [17]:
swandlondon0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1216 entries, 0 to 1215
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MSOA11CD  1216 non-null   object
 1   MSOA11NM  1216 non-null   object
 2   LAD11CD   1216 non-null   object
 3   LAD11NM   1216 non-null   object
 4   RGN11CD   1216 non-null   object
 5   RGN11NM   1216 non-null   object
 6   MSOA01CD  1216 non-null   object
 7   MSOA01NM  1216 non-null   object
 8   CHGIND    1216 non-null   object
dtypes: object(9)
memory usage: 85.6+ KB

### Socio-demographics and Build Environment Data

#### House Price Data

In [18]:
#read in median house price of 2001 and 2011 for all MSOAs
medianprice_2011 = pd.read_csv('data01/median_price_2011.csv')
medianprice_2001 = pd.read_csv('data01/median_price_2001.csv')
#read in median house price of 2001 and 2011 for all local authorities 
medianprice_la = pd.read_csv('data01/median_price_la.csv')
#read in median house price of 2001 and 2011 for all regions 
medianprice_r = pd.read_csv('data01/median_price_reigion.csv')

#### Income Data (lack of 2001 MSOA level data)

In [19]:
#read in mean income of 2011 for all MSOAs
meanincome_2011 = pd.read_csv('data01/mean_earning_2011.csv')
#read in mean income of 2001 and 2011 for all local authorities
meanincome_la = pd.read_csv('data01/mean_earning_la.csv')
#read in mean income of 2001 and 2011 for all regions
meanincome_r = pd.read_csv('data01/mean_earning_region.csv')

#### NS-SeC Data (occupation condition)

In [20]:
#read in NS-SeC data of 2001 and 2011 for all MSOAs
nssec_2011 = pd.read_csv('data01/NS-SeC_2011.csv')
nssec_2001 = pd.read_csv('data01/NS-SeC_2001.csv')
#read in NS-SeC data of 2001 and 2011 for all local authorities 
nssec_2011_la = pd.read_csv('data01/NS-SeC_2011_la.csv')
nssec_2001_la = pd.read_csv('data01/NS-SeC_2001_la.csv')
#read in NS-SeC data of 2001 and 2011 for all regions 
nssec_2011_r = pd.read_csv('data01/NS-SeC_2011_region.csv')
nssec_2001_r = pd.read_csv('data01/NS-SeC_2001_region.csv')

#### Qualification Data

In [21]:
#read in qualification data of 2001 and 2011 for all MSOAs
qualification_2011 = pd.read_csv('data01/qualification_2011.csv')
qualification_2001 = pd.read_csv('data01/qualification_2001.csv')
#read in qualification data of 2001 and 2011 for all local authorities 
qualification_2011_la = pd.read_csv('data01/qualifications_2011_la.csv')
qualification_2001_la = pd.read_csv('data01/qualifications_2001_la.csv')
#read in qualification data of 2001 and 2011 for all regions 
qualification_2011_r = pd.read_csv('data01/qualifications_2011_region.csv')
qualification_2001_r = pd.read_csv('data01/qualifications_2001_region.csv')

#### Household Space Data (vacant ones are represented for the level of second homes)

In [22]:
#read in Household Space Data of 2001 and 2011 for all MSOAs
space_2001 = pd.read_csv('data02/householdspace_2001.csv')
space_2011 = pd.read_csv('data02/householdspace_2011.csv')
#read in Household Space Data of 2001 and 2011 for all local authorities
space_2001_la = pd.read_csv('data02/householdspace_2001_la.csv')
space_2011_la = pd.read_csv('data02/householdspace_2011_la.csv')

#### Household Component Data (mainly focus on the children)

In [23]:
#read in Household Component Data of 2001 and 2011 for all MSOAs
children_2001 = pd.read_csv('data03/children_2001.csv')
children_2011 = pd.read_csv('data03/children_2011.csv')
#read in Household Component Data of 2001 and 2011 for all local authorities
children_2001_la = pd.read_csv('data03/children_2001_la.csv')
children_2011_la = pd.read_csv('data03/children_2011_la.csv')

#### Economic Activty Data (mainly focus on the retired population)

In [24]:
#read in Economic Activty Data of 2001 and 2011 for all MSOAs
eco_2001 = pd.read_csv('data03/economic_activity_2001.csv')
eco_2011 = pd.read_csv('data03/economic_activity_2011.csv')
#read in Economic Activty Data of 2001 and 2011 for all local authorities
eco_2001_la = pd.read_csv('data03/economic_activity_2001_la.csv')
eco_2011_la = pd.read_csv('data03/economic_activity_2011_la.csv')

#### Migration Data (lack of Migration data of 2001 for MSOA level)

In [25]:
#read in Migration Data of 2001 and 2011 for all MSOAs
migration_2011 = pd.read_csv('data03/migration_2011.csv')
#read in Migaration Data of 2001 and 2011 for all local authorities
migration_2001_la = pd.read_csv('data03/migration_2001_la.csv')
migration_2011_la = pd.read_csv('data03/migration_2011_la.csv')

#### Residential Property Sale Data

In [26]:
#read in Residential Property Sale Data of 2001 and 2011 for all MSOAs
sale= pd.read_csv('data03/residential_property_sale.csv')
#read in Residential Property Sale Data of 2001 and 2011 for all local authorities
sale_la = pd.read_csv('data03/residential_property_sale_la.csv')

#### Tenure Data

In [27]:
#read in Tenure Data of 2001 and 2011 for all MSOAs
tenure_2001 = pd.read_csv('data03/tenure_2001.csv')
tenure_2011 = pd.read_csv('data03/tenure_2011.csv')
#read in Tenure Data of 2001 and 2011 for all local authorities
tenure_2001_la = pd.read_csv('data03/tenure_2001_la.csv')
tenure_2011_la = pd.read_csv('data03/tenure_2011_la.csv')

Merge all demographic and housing data to the 'swandlondon0' dataset

In [28]:
swandlondon0 = swandlondon0.merge(medianprice_2001, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(medianprice_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(medianprice_la, on='LAD11CD', how='left')
swandlondon0 = swandlondon0.merge(medianprice_r, on='RGN11CD', how='left')

In [29]:
swandlondon0 = swandlondon0.merge(meanincome_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(meanincome_la, on='LAD11CD', how='left')
swandlondon0 = swandlondon0.merge(meanincome_r, on='RGN11NM', how='left')

In [30]:
swandlondon0 = swandlondon0.merge(nssec_2001, on='MSOA01CD', how='left')
swandlondon0 = swandlondon0.merge(nssec_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(nssec_2001_la, on='LAD11NM', how='left')
swandlondon0 = swandlondon0.merge(nssec_2011_la, on='LAD11NM', how='left')
swandlondon0 = swandlondon0.merge(nssec_2001_r, on='RGN11NM', how='left')
swandlondon0 = swandlondon0.merge(nssec_2011_r, on='RGN11NM', how='left')
swandlondon0 = swandlondon0.merge(qualification_2001, on='MSOA01CD', how='left')
swandlondon0 = swandlondon0.merge(qualification_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(qualification_2001_la, on='LAD11NM', how='left')
swandlondon0 = swandlondon0.merge(qualification_2011_la, on='LAD11NM', how='left')
swandlondon0 = swandlondon0.merge(qualification_2001_r, on='RGN11NM', how='left')
swandlondon0 = swandlondon0.merge(qualification_2011_r, on='RGN11NM', how='left')

In [31]:
swandlondon0 = swandlondon0.merge(space_2001, on='MSOA01CD', how='left')
swandlondon0 = swandlondon0.merge(space_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(space_2001_la, on='LAD11CD', how='left')
swandlondon0 = swandlondon0.merge(space_2011_la, on='LAD11CD', how='left')

In [32]:
swandlondon0 = swandlondon0.merge(children_2001, on='MSOA01CD', how='left')
swandlondon0 = swandlondon0.merge(children_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(children_2001_la, on='LAD11NM', how='left')
swandlondon0 = swandlondon0.merge(children_2011_la, on='LAD11NM', how='left')

In [33]:
swandlondon0 = swandlondon0.merge(eco_2001, on='MSOA01CD', how='left')
swandlondon0 = swandlondon0.merge(eco_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(eco_2001_la, on='LAD11NM', how='left')
swandlondon0 = swandlondon0.merge(eco_2011_la, on='LAD11NM', how='left')

In [34]:
swandlondon0 = swandlondon0.merge(migration_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(migration_2001_la, on='LAD11NM', how='left')
swandlondon0 = swandlondon0.merge(migration_2011_la, on='LAD11NM', how='left')

In [35]:
swandlondon0 = swandlondon0.merge(sale, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(sale_la, on='LAD11CD', how='left')

In [36]:
swandlondon0 = swandlondon0.merge(tenure_2001, on='MSOA01CD', how='left')
swandlondon0 = swandlondon0.merge(tenure_2011, on='MSOA11CD', how='left')
swandlondon0 = swandlondon0.merge(tenure_2001_la, on='LAD11NM', how='left')
swandlondon0 = swandlondon0.merge(tenure_2011_la, on='LAD11NM', how='left')

In [37]:
swandlondon0.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1216 entries, 0 to 1215
Data columns (total 157 columns):
 #   Column                             Dtype
---  ------                             -----
 0   MSOA11CD                           object
 1   MSOA11NM                           object
 2   LAD11CD                            object
 3   LAD11NM                            object
 4   RGN11CD                            object
 5   RGN11NM                            object
 6   MSOA01CD                           object
 7   MSOA01NM                           object
 8   CHGIND                             object
 9   median_price_2001                  float64
 10  median_price_2011                  object
 11  median_price_2001_la               int64
 12  median_price_2011_la               int64
 13  median_price_2001_region           int64
 14  median_price_2011_region           int64
 15  earnings_2011                      float64
 16  earnings_2001_la                   int64
 17  earnings_2011_la                   float64
 18  earnings_2001_region               int64
 19  earnings_2011_region               int64
 20  NS-SeC_all_2001                    int64
 21  NS-SeC_higher_2001                 int64
 22  NS-SeC_higher_2001_pct             float64
 23  NS-SeC_all_2011                    object
 24  NS-SeC_higher_2011                 float64
 25  NS-SeC_higher_2011_pct             float64
 26  NS-SeC_all_2001_la                 int64
 27  NS-SeC_higher_2001_la              int64
 28  NS-SeC_higher_2001_la_pct          float64
 29  NS-SeC_all_2011_la                 int64
 30  NS-SeC_higher_2011_la              int64
 31  NS-SeC_higher_2011_la_pct          float64
 32  NS-SeC_all_2001_region             int64
 33  NS-SeC_higher_2001_region          int64
 34  NS-SeC_higher_2001_region_pct      float64
 35  NS-SeC_all_2011_region             int64
 36  NS-SeC_higher_2011_region          int64
 37  NS-SeC_higher_2011_region_pct      float64
 38  qualification_all_2001             object
 39  qualification_2001                 float64
 40  qualification_2001_pct             float64
 41  qualification_all_2011             object
 42  qualification_2011                 float64
 43  qualification_2011_pct             float64
 44  qualification_all_2001_la          int64
 45  qualification_2001_la              int64
 46  qualification_2001_la_pct          float64
 47  qualification_all_2011_la          int64
 48  qualification_2011_la              int64
 49  qualification_2011_la_pct          float64
 50  qualification_all_2001_region      int64
 51  qualification_2001_region          int64
 52  qualification_2001_region_pct      float64
 53  qualification_all_2011_region      int64
 54  qualification_2011_region          int64
 55  qualification_2011_region_pct      float64
 56  space_all_2001                     int64
 57  space_vacant_2001                  int64
 58  space_vacant_2001_pct              float64
 59  space_all_2011                     int64
 60  space_vacant_2011                  int64
 61  space_vacant_2011_pct              float64
 62  space_all_2001_la                  int64
 63  space_vacant_2001_la               int64
 64  space_vacant_2001_la_pct           float64
 65  space_all_2011_la                  int64
 66  space_vacant_2011_la               int64
 67  space_vacant_2011_la_pct           float64
 68  all_households_2001                object
 69  no_children_2001                   float64
 70  dependent_children_2001            float64
 71  nondependent_children_2001         float64
 72  no_children_2001_pct               float64
 73  dependent_children_2001_pct        float64
 74  nondependent_children_2001_pct     float64
 75  all_households_2011                object
 76  no_children_2011                   float64
 77  dependent_children_2011            float64
 78  nondependent_children_2011         float64
 79  no_children_2011_pct               float64
 80  dependent_children_2011_pct        float64
 81  nondependent_children_2011_pct     float64
 82  all_households_2001_la             object
 83  no_children_2001_la                float64
 84  dependent_children_2001_la         float64
 85  nondependent_children_2001_la      float64
 86  no_children_2001_la_pct            float64
 87  dependent_children_2001_la_pct     float64
 88  nondependent_children_2001_la_pct  float64
 89  all_households_2011_la             object
 90  no_children_2011_la                float64
 91  dependent_children_2011_la         float64
 92  nondependent_children_2011_la      float64
 93  no_children_2011_la_pct            float64
 94  dependent_children_2011_la_pct     float64
 95  nondependent_children_2011_la_pct  float64
 96  economically_inactive_2001         int64
 97  retired_2001                       int64
 98  student_2001                       int64
 99  retired_2001_pct                   float64
 100 student_2001_pct                   float64
 101 economically_inactive_2011         int64
 102 retired_2011                       int64
 103 student_2011                       int64
 104 retired_2011_pct                   float64
 105 student_2011_pct                   float64
 106 economically_inactive_2001_la      float64
 107 retired_2001_la                    float64
 108 student_2001_la                    float64
 109 retired_2001_la_pct                float64
 110 student_2001_la_pct                float64
 111 economically_inactive_2011_la      float64
 112 retired_2011_la                    float64
 113 student_2011_la                    float64
 114 retired_2011_la_pct                float64
 115 student_2011_la_pct                float64
 116 residents_all_2011                 int64
 117 migrants_2011                      int64
 118 migrants_2011_pct                  float64
 119 residents_all_2001_la              object
 120 migrants_2001_la                   object
 121 migrants_2001_la_pct               object
 122 residents_all_2011_la              float64
 123 migrants_2011_la                   float64
 124 migrants_2011_la_pct               float64
 125 residential_sale_2001              int64
 126 residential_sale_2011              int64
 127 newlybuilt_sale_2001               int64
 128 newlybuilt_sale_2011               int64
 129 newlybuilt_sale_2001_pct           float64
 130 newlybuilt_sale_2011_pct           float64
 131 residential_sale_2001_la           int64
 132 residential__sale_2011_la          int64
 133 newlybuilt_sale_2001_la            int64
 134 newlybuilt_sale_2011_la            int64
 135 newlybuilt_sale_2001_la_pct        float64
 136 newlybuilt_sale_2011_la_pct        float64
 137 tenure_all_2001                    object
 138 owned_2001                         float64
 139 rented_2001                        float64
 140 owned_2001_pct                     float64
 141 rented_2001_pct                    float64
 142 tenure_all_2011                    object
 143 owned_2011                         float64
 144 rented_2011                        float64
 145 owned_2011_pct                     float64
 146 rented_2011_pct                    float64
 147 tenure_all_2001_la                 float64
 148 owned_2001_la                      float64
 149 rented_2001_la                     float64
 150 owned_2001_la_pct                  float64
 151 rented_2001_la_pct                 float64
 152 tenure_all_2011_la                 object
 153 owned_2011_la                      float64
 154 rented_2011_la                     float64
 155 owned_2011_la_pct                  float64
 156 rented_2011_la_pct                 float64
dtypes: float64(85), int64(49), object(23)
memory usage: 1.5+ MB

In [38]:
#extract the rows whose 'CHGING' value is M. The percentage value of the 2001 variables of these rows should be recalculated
swandlondon0_sub1=swandlondon0[(swandlondon0['CHGIND']=='X')|(swandlondon0['CHGIND']=='U')|(swandlondon0['CHGIND']=='S')].copy()
swandlondon0_subm=swandlondon0[swandlondon0['CHGIND']=='M'].copy()

In [39]:
swandlondon0_sub1.info()
swandlondon0_subm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1206 entries, 0 to 1215
Columns: 157 entries, MSOA11CD to rented_2011_la_pct
dtypes: float64(85), int64(49), object(23)
memory usage: 1.5+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 228 to 1205
Columns: 157 entries, MSOA11CD to rented_2011_la_pct
dtypes: float64(85), int64(49), object(23)
memory usage: 12.3+ KB

In [40]:
swandlondon0_subm.head(10)

,MSOA11CD,MSOA11NM,LAD11CD,LAD11NM,RGN11CD,RGN11NM,MSOA01CD,MSOA01NM,CHGIND,median_price_2001,...,tenure_all_2001_la,owned_2001_la,rented_2001_la,owned_2001_la_pct,rented_2001_la_pct,tenure_all_2011_la,owned_2011_la,rented_2011_la,owned_2011_la_pct,rented_2011_la_pct
228,E02006840,Torbay 019,E06000027,Torbay,E12000009,South West,E02003160,Torbay 007,M,84500.0,...,57420.0,41907.0,13403.0,0.729833,0.233420,59010,39424.0,18458.0,0.668090,0.312794
229,E02006840,Torbay 019,E06000027,Torbay,E12000009,South West,E02003162,Torbay 009,M,84500.0,...,57420.0,41907.0,13403.0,0.729833,0.233420,59010,39424.0,18458.0,0.668090,0.312794
1183,E02006924,Redbridge 035,E09000026,Redbridge,E12000007,London,E02000771,Redbridge 021,M,165000.0,...,92288.0,69008.0,20480.0,0.747746,0.221914,99105,62983.0,33946.0,0.635518,0.342526
1184,E02006924,Redbridge 035,E09000026,Redbridge,E12000007,London,E02000775,Redbridge 025,M,165000.0,...,92288.0,69008.0,20480.0,0.747746,0.221914,99105,62983.0,33946.0,0.635518,0.342526
1185,E02006925,Redbridge 036,E09000026,Redbridge,E12000007,London,E02000761,Redbridge 011,M,185000.0,...,92288.0,69008.0,20480.0,0.747746,0.221914,99105,62983.0,33946.0,0.635518,0.342526
1186,E02006925,Redbridge 036,E09000026,Redbridge,E12000007,London,E02000766,Redbridge 016,M,185000.0,...,92288.0,69008.0,20480.0,0.747746,0.221914,99105,62983.0,33946.0,0.635518,0.342526
1187,E02006927,Greenwich 034,E09000011,Greenwich,E12000007,London,E02000336,Greenwich 024,M,127500.0,...,92788.0,44870.0,44929.0,0.483575,0.484211,101045,43719.0,54666.0,0.432669,0.541006
1188,E02006927,Greenwich 034,E09000011,Greenwich,E12000007,London,E02000338,Greenwich 026,M,127500.0,...,92788.0,44870.0,44929.0,0.483575,0.484211,101045,43719.0,54666.0,0.432669,0.541006
1204,E02006882,Harrow 033,E09000015,Harrow,E12000007,London,E02000450,Harrow 018,M,182250.0,...,79112.0,58755.0,17113.0,0.742681,0.216314,84268,55001.0,27247.0,0.652691,0.323337
1205,E02006882,Harrow 033,E09000015,Harrow,E12000007,London,E02000446,Harrow 014,M,182250.0,...,79112.0,58755.0,17113.0,0.742681,0.216314,84268,55001.0,27247.0,0.652691,0.323337

In [41]:
#for the rows whose 'CHGING' value is M, recalculation is carred out seperately in Excel
swandlondon0_subm.to_csv('output/swandlondon0_subm.csv',index=False)

In [42]:
#read in th the dataset after recalulation and compare it with the original one.
swandlondon0_subm_after = pd.read_csv('output/swandlondon0_subm_after.csv')

In [43]:
pd.set_option("display.max_columns", None)
swandlondon0_subm_after.head(5)

,MSOA11CD,MSOA11NM,LAD11CD,LAD11NM,RGN11CD,RGN11NM,MSOA01CD,MSOA01NM,CHGIND,median_price_2001,median_price_2011,median_price_2001_la,median_price_2011_la,median_price_2001_region,median_price_2011_region,earnings_2011,earnings_2001_la,earnings_2011_la,earnings_2001_region,earnings_2011_region,NS-SeC_all_2001,NS-SeC_higher_2001,NS-SeC_higher_2001_pct,NS-SeC_all_2011,NS-SeC_higher_2011,NS-SeC_higher_2011_pct,NS-SeC_all_2001_la,NS-SeC_higher_2001_la,NS-SeC_higher_2001_la_pct,NS-SeC_all_2011_la,NS-SeC_higher_2011_la,NS-SeC_higher_2011_la_pct,NS-SeC_all_2001_region,NS-SeC_higher_2001_region,NS-SeC_higher_2001_region_pct,NS-SeC_all_2011_region,NS-SeC_higher_2011_region,NS-SeC_higher_2011_region_pct,qualification_all_2001,qualification_2001,qualification_2001_pct,qualification_all_2011,qualification_2011,qualification_2011_pct,qualification_all_2001_la,qualification_2001_la,qualification_2001_la_pct,qualification_all_2011_la,qualification_2011_la,qualification_2011_la_pct,qualification_all_2001_region,qualification_2001_region,qualification_2001_region_pct,qualification_all_2011_region,qualification_2011_region,qualification_2011_region_pct,space_all_2001,space_vacant_2001,space_vacant_2001_pct,space_all_2011,space_vacant_2011,space_vacant_2011_pct,space_all_2001_la,space_vacant_2001_la,space_vacant_2001_la_pct,space_all_2011_la,space_vacant_2011_la,space_vacant_2011_la_pct,all_households_2001,no_children_2001,dependent_children_2001,nondependent_children_2001,no_children_2001_pct,dependent_children_2001_pct,nondependent_children_2001_pct,all_households_2011,no_children_2011,dependent_children_2011,nondependent_children_2011,no_children_2011_pct,dependent_children_2011_pct,nondependent_children_2011_pct,all_households_2001_la,no_children_2001_la,dependent_children_2001_la,nondependent_children_2001_la,no_children_2001_la_pct,dependent_children_2001_la_pct,nondependent_children_2001_la_pct,all_households_2011_la,no_children_2011_la,dependent_children_2011_la,nondependent_children_2011_la,no_children_2011_la_pct,dependent_children_2011_la_pct,nondependent_children_2011_la_pct,economically_inactive_2001,retired_2001,student_2001,retired_2001_pct,student_2001_pct,economically_inactive_2011,retired_2011,student_2011,retired_2011_pct,student_2011_pct,economically_inactive_2001_la,retired_2001_la,student_2001_la,retired_2001_la_pct,student_2001_la_pct,economically_inactive_2011_la,retired_2011_la,student_2011_la,retired_2011_la_pct,student_2011_la_pct,residents_all_2011,migrants_2011,migrants_2011_pct,residents_all_2001_la,migrants_2001_la,migrants_2001_la_pct,residents_all_2011_la,migrants_2011_la,migrants_2011_la_pct,residential_sale_2001,residential_sale_2011,newlybuilt_sale_2001,newlybuilt_sale_2011,newlybuilt_sale_2001_pct,newlybuilt_sale_2011_pct,residential_sale_2001_la,residential__sale_2011_la,newlybuilt_sale_2001_la,newlybuilt_sale_2011_la,newlybuilt_sale_2001_la_pct,newlybuilt_sale_2011_la_pct,tenure_all_2001,owned_2001,rented_2001,owned_2001_pct,rented_2001_pct,tenure_all_2011,owned_2011,rented_2011,owned_2011_pct,rented_2011_pct,tenure_all_2001_la,owned_2001_la,rented_2001_la,owned_2001_la_pct,rented_2001_la_pct,tenure_all_2011_la,owned_2011_la,rented_2011_la,owned_2011_la_pct,rented_2011_la_pct
0,E02006840,Torbay 019,E06000027,Torbay,E12000009,South West,E02003160,Torbay 007,M,84500,180000,82500,160000,96500,185000,14913.78,11300,15397,12777,16958,7807,1841,0.235814,7523,2319,0.308255,90852,19026,0.209418,94000,24528,0.260936,3534458,931080,0.263429,3856715,1229068,0.318683,7807,1183,0.151531,8667,2163,0.249567,90852,12286,0.135231,109290,22564,0.206460,3534458,665869,0.188394,4359257,1193337,0.273748,4744,141,0.029722,4806,305,0.063462,60479,3059,0.050580,64370,5360,0.083269,4601,827,1245,361,0.179744,0.270593,0.078461,4501,816,1162,409,0.181293,0.258165,0.090869,57420,10011,14158,4374,0.174347,0.246569,0.076176,59010,10580,13192,4850,0.179292,0.223555,0.082189,2615,1275,233,0.487572,0.089101,2350,1362,269,0.579574,0.114468,33322,16321,2372,0.489797,0.071184,32205,18416,3032,0.571837,0.094147,10636,851,0.080011,129706,6164,0.047523,130959,4938,0.037706,303,143,4,8,0.013201,0.055944,4417,1977,272,146,0.061580,0.073849,4603,3589,878,0.779709,0.190745,4501,3367,1089,0.748056,0.241946,57420,41907,13403,0.729833,0.233420,59010,39424,18458,0.668090,0.312794
1,E02006924,Redbridge 035,E09000026,Redbridge,E12000007,London,E02000771,Redbridge 021,M,165000,325000,138500,250000,155000,292688,14867.94,13804,17550,16119,22030,8643,2799,0.323846,9356,2955,0.315840,171300,53108,0.310029,199544,65964,0.330574,5300332,1818255,0.343045,6117482,2218721,0.362685,8643,2575,0.297929,10157,3781,0.372256,171300,40811,0.238243,216112,73299,0.339171,5300332,1642467,0.309880,6549173,2470225,0.377181,4213,119,0.028246,4121,101,0.024509,94174,1886,0.020027,101575,2470,0.024317,4094,477,1103,532,0.116512,0.269419,0.129946,4020,371,1111,562,0.092289,0.276368,0.139801,92288,12434,28403,10352,0.134730,0.307765,0.112171,99105,11804,31272,11409,0.119106,0.315544,0.115120,3061,912,712,0.297942,0.232604,3235,951,944,0.293972,0.291808,58007,19389,11009,0.334253,0.189787,61768,19026,16199,0.308024,0.262256,12780,963,0.075352,238635,11993,0.050257,278970,14898,0.053404,180,92,0,0,0.000000,0.000000,5780,2539,367,80,0.063495,0.031508,4094,3155,831,0.770640,0.202980,4020,2748,1220,0.683582,0.303483,92288,69008,20480,0.747746,0.221914,99105,62983,33946,0.635518,0.342526
2,E02006925,Redbridge 036,E09000026,Redbridge,E12000007,London,E02000761,Redbridge 011,M,185000,326750,138500,250000,155000,292688,16547.20,13804,17550,16119,22030,8554,2674,0.312602,9417,3208,0.340661,171300,53108,0.310029,199544,65964,0.330574,5300332,1818255,0.343045,6117482,2218721,0.362685,8554,2046,0.239186,10341,3521,0.340489,171300,40811,0.238243,216112,73299,0.339171,5300332,1642467,0.309880,6549173,2470225,0.377181,4190,54,0.012888,4181,79,0.018895,94174,1886,0.020027,101575,2470,0.024317,4139,506,1337,657,0.122252,0.323025,0.158734,4102,362,1356,657,0.088250,0.330570,0.160166,92288,12434,28403,10352,0.134730,0.307765,0.112171,99105,11804,31272,11409,0.119106,0.315544,0.115120,2862,1037,620,0.362334,0.216632,2955,1002,935,0.339086,0.316413,58007,19389,11009,0.334253,0.189787,61768,19026,16199,0.308024,0.262256,13241,858,0.064799,238635,11993,0.050257,278970,14898,0.053404,202,110,1,0,0.004950,0.000000,5780,2539,367,80,0.063495,0.031508,4136,3601,456,0.870648,0.110251,4102,3313,731,0.807655,0.178206,92288,69008,20480,0.747746,0.221914,99105,62983,33946,0.635518,0.342526
3,E02006927,Greenwich 034,E09000011,Greenwich,E12000007,London,E02000336,Greenwich 024,M,127500,280000,124995,249995,155000,292688,19259.60,15592,19069,16119,22030,7992,2363,0.295671,5910,2228,0.376988,153795,44042,0.286368,186722,58787,0.314837,5300332,1818255,0.343045,6117482,2218721,0.362685,7992,2103,0.263138,6566,2435,0.370850,153795,36439,0.236932,199163,66120,0.331989,5300332,1642467,0.309880,6549173,2470225,0.377181,5030,78,0.015507,3449,111,0.032183,95835,3047,0.031794,103827,2782,0.026795,4951,589,1375,435,0.118966,0.277722,0.087861,3338,441,894,378,0.132115,0.267825,0.113241,92788,11786,26372,8185,0.127021,0.284218,0.088212,101045,13402,28602,9200,0.132634,0.283062,0.091049,2939,874,524,0.297380,0.178292,1891,702,408,0.371232,0.215759,52759,15903,9400,0.301427,0.178169,54649,15695,13957,0.287196,0.255394,8315,657,0.079014,214403,11798,0.055027,254557,16607,0.065239,146,116,0,12,0.000000,0.103448,4839,2570,899,422,0.185782,0.164202,4952,2180,2612,0.440226,0.527464,3338,1924,1352,0.576393,0.405033,92788,44870,44929,0.483575,0.484211,101045,43719,54666,0.432669,0.541006
4,E02006882,Harrow 033,E09000015,Harrow,E12000007,London,E02000450,Harrow 018,M,182250,315000,166000,294500,155000,292688,15160.69,16118,21231,16119,22030,9574,2891,0.301964,10757,3228,0.300084,150514,52113,0.346234,174751,61481,0.351821,5300332,1818255,0.343045,6117482,2218721,0.362685,9574,2413,0.252037,11628,3885,0.334107,150514,44297,0.294305,190998,70218,0.367637,5300332,1642467,0.309880,6549173,2470225,0.377181,4334,84,0.019382,4403,61,0.013854,80904,1792,0.022150,86667,2399,0.027681,4250,478,1458,653,0.112471,0.343059,0.153647,4342,461,1195,825,0.106172,0.275219,0.190005,79112,10962,23941,9294,0.138563,0.302622,0.117479,84268,10341,24829,11412,0.122716,0.294643,0.135425,3072,1012,723,0.329427,0.235352,3120,1182,854,0.378846,0.273718,47465,16913,9474,0.356326,0.199600,51444,18189,13417,0.353569,0.260808,14174,982,0.069282,206814,9968,0.048198,239056,11786,0.049302,168,79,0,0,0.000000,0.000000,4349,2168,205,141,0.047137,0.065037,4250,3528,548,0.830118,0.128941,4342,3333,893,0.767619,0.205666,79112,58755,17113,0.742681,0.216314,84268,55001,27247,0.652691,0.323337

In [44]:
#conbime tow datasets to get the final complete dataset contains all raw data
swandlondon = pd.concat([swandlondon0_sub1, swandlondon0_subm_after],ignore_index=True)

In [45]:
swandlondon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1211 entries, 0 to 1210
Columns: 157 entries, MSOA11CD to rented_2011_la_pct
dtypes: float64(85), int64(49), object(23)
memory usage: 1.5+ MB

In [46]:
swandlondon.to_csv('output/swandlondon.csv',index=False)

---

## Create Ratio Variables

In [47]:
swandlondon = pd.read_csv('output/swandlondon.csv')
swandlondon.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1211 entries, 0 to 1210
Data columns (total 157 columns):
 #   Column                             Dtype
---  ------                             -----
 0   MSOA11CD                           object
 1   MSOA11NM                           object
 2   LAD11CD                            object
 3   LAD11NM                            object
 4   RGN11CD                            object
 5   RGN11NM                            object
 6   MSOA01CD                           object
 7   MSOA01NM                           object
 8   CHGIND                             object
 9   median_price_2001                  float64
 10  median_price_2011                  int64
 11  median_price_2001_la               int64
 12  median_price_2011_la               int64
 13  median_price_2001_region           int64
 14  median_price_2011_region           int64
 15  earnings_2011                      float64
 16  earnings_2001_la                   int64
 17  earnings_2011_la                   float64
 18  earnings_2001_region               int64
 19  earnings_2011_region               int64
 20  NS-SeC_all_2001                    int64
 21  NS-SeC_higher_2001                 int64
 22  NS-SeC_higher_2001_pct             float64
 23  NS-SeC_all_2011                    int64
 24  NS-SeC_higher_2011                 float64
 25  NS-SeC_higher_2011_pct             float64
 26  NS-SeC_all_2001_la                 int64
 27  NS-SeC_higher_2001_la              int64
 28  NS-SeC_higher_2001_la_pct          float64
 29  NS-SeC_all_2011_la                 int64
 30  NS-SeC_higher_2011_la              int64
 31  NS-SeC_higher_2011_la_pct          float64
 32  NS-SeC_all_2001_region             int64
 33  NS-SeC_higher_2001_region          int64
 34  NS-SeC_higher_2001_region_pct      float64
 35  NS-SeC_all_2011_region             int64
 36  NS-SeC_higher_2011_region          int64
 37  NS-SeC_higher_2011_region_pct      float64
 38  qualification_all_2001             int64
 39  qualification_2001                 float64
 40  qualification_2001_pct             float64
 41  qualification_all_2011             int64
 42  qualification_2011                 float64
 43  qualification_2011_pct             float64
 44  qualification_all_2001_la          int64
 45  qualification_2001_la              int64
 46  qualification_2001_la_pct          float64
 47  qualification_all_2011_la          int64
 48  qualification_2011_la              int64
 49  qualification_2011_la_pct          float64
 50  qualification_all_2001_region      int64
 51  qualification_2001_region          int64
 52  qualification_2001_region_pct      float64
 53  qualification_all_2011_region      int64
 54  qualification_2011_region          int64
 55  qualification_2011_region_pct      float64
 56  space_all_2001                     int64
 57  space_vacant_2001                  int64
 58  space_vacant_2001_pct              float64
 59  space_all_2011                     int64
 60  space_vacant_2011                  int64
 61  space_vacant_2011_pct              float64
 62  space_all_2001_la                  int64
 63  space_vacant_2001_la               int64
 64  space_vacant_2001_la_pct           float64
 65  space_all_2011_la                  int64
 66  space_vacant_2011_la               int64
 67  space_vacant_2011_la_pct           float64
 68  all_households_2001                int64
 69  no_children_2001                   float64
 70  dependent_children_2001            float64
 71  nondependent_children_2001         float64
 72  no_children_2001_pct               float64
 73  dependent_children_2001_pct        float64
 74  nondependent_children_2001_pct     float64
 75  all_households_2011                int64
 76  no_children_2011                   float64
 77  dependent_children_2011            float64
 78  nondependent_children_2011         float64
 79  no_children_2011_pct               float64
 80  dependent_children_2011_pct        float64
 81  nondependent_children_2011_pct     float64
 82  all_households_2001_la             int64
 83  no_children_2001_la                float64
 84  dependent_children_2001_la         float64
 85  nondependent_children_2001_la      float64
 86  no_children_2001_la_pct            float64
 87  dependent_children_2001_la_pct     float64
 88  nondependent_children_2001_la_pct  float64
 89  all_households_2011_la             int64
 90  no_children_2011_la                float64
 91  dependent_children_2011_la         float64
 92  nondependent_children_2011_la      float64
 93  no_children_2011_la_pct            float64
 94  dependent_children_2011_la_pct     float64
 95  nondependent_children_2011_la_pct  float64
 96  economically_inactive_2001         int64
 97  retired_2001                       int64
 98  student_2001                       int64
 99  retired_2001_pct                   float64
 100 student_2001_pct                   float64
 101 economically_inactive_2011         int64
 102 retired_2011                       int64
 103 student_2011                       int64
 104 retired_2011_pct                   float64
 105 student_2011_pct                   float64
 106 economically_inactive_2001_la      float64
 107 retired_2001_la                    float64
 108 student_2001_la                    float64
 109 retired_2001_la_pct                float64
 110 student_2001_la_pct                float64
 111 economically_inactive_2011_la      float64
 112 retired_2011_la                    float64
 113 student_2011_la                    float64
 114 retired_2011_la_pct                float64
 115 student_2011_la_pct                float64
 116 residents_all_2011                 int64
 117 migrants_2011                      int64
 118 migrants_2011_pct                  float64
 119 residents_all_2001_la              int64
 120 migrants_2001_la                   int64
 121 migrants_2001_la_pct               float64
 122 residents_all_2011_la              float64
 123 migrants_2011_la                   float64
 124 migrants_2011_la_pct               float64
 125 residential_sale_2001              int64
 126 residential_sale_2011              int64
 127 newlybuilt_sale_2001               int64
 128 newlybuilt_sale_2011               int64
 129 newlybuilt_sale_2001_pct           float64
 130 newlybuilt_sale_2011_pct           float64
 131 residential_sale_2001_la           int64
 132 residential__sale_2011_la          int64
 133 newlybuilt_sale_2001_la            int64
 134 newlybuilt_sale_2011_la            int64
 135 newlybuilt_sale_2001_la_pct        float64
 136 newlybuilt_sale_2011_la_pct        float64
 137 tenure_all_2001                    int64
 138 owned_2001                         float64
 139 rented_2001                        float64
 140 owned_2001_pct                     float64
 141 rented_2001_pct                    float64
 142 tenure_all_2011                    int64
 143 owned_2011                         float64
 144 rented_2011                        float64
 145 owned_2011_pct                     float64
 146 rented_2011_pct                    float64
 147 tenure_all_2001_la                 float64
 148 owned_2001_la                      float64
 149 rented_2001_la                     float64
 150 owned_2001_la_pct                  float64
 151 rented_2001_la_pct                 float64
 152 tenure_all_2011_la                 int64
 153 owned_2011_la                      float64
 154 rented_2011_la                     float64
 155 owned_2011_la_pct                  float64
 156 rented_2011_la_pct                 float64
dtypes: float64(86), int64(62), object(9)
memory usage: 1.5+ MB

In [48]:
swandlondon.tail()

,MSOA11CD,MSOA11NM,LAD11CD,LAD11NM,RGN11CD,RGN11NM,MSOA01CD,MSOA01NM,CHGIND,median_price_2001,median_price_2011,median_price_2001_la,median_price_2011_la,median_price_2001_region,median_price_2011_region,earnings_2011,earnings_2001_la,earnings_2011_la,earnings_2001_region,earnings_2011_region,NS-SeC_all_2001,NS-SeC_higher_2001,NS-SeC_higher_2001_pct,NS-SeC_all_2011,NS-SeC_higher_2011,NS-SeC_higher_2011_pct,NS-SeC_all_2001_la,NS-SeC_higher_2001_la,NS-SeC_higher_2001_la_pct,NS-SeC_all_2011_la,NS-SeC_higher_2011_la,NS-SeC_higher_2011_la_pct,NS-SeC_all_2001_region,NS-SeC_higher_2001_region,NS-SeC_higher_2001_region_pct,NS-SeC_all_2011_region,NS-SeC_higher_2011_region,NS-SeC_higher_2011_region_pct,qualification_all_2001,qualification_2001,qualification_2001_pct,qualification_all_2011,qualification_2011,qualification_2011_pct,qualification_all_2001_la,qualification_2001_la,qualification_2001_la_pct,qualification_all_2011_la,qualification_2011_la,qualification_2011_la_pct,qualification_all_2001_region,qualification_2001_region,qualification_2001_region_pct,qualification_all_2011_region,qualification_2011_region,qualification_2011_region_pct,space_all_2001,space_vacant_2001,space_vacant_2001_pct,space_all_2011,space_vacant_2011,space_vacant_2011_pct,space_all_2001_la,space_vacant_2001_la,space_vacant_2001_la_pct,space_all_2011_la,space_vacant_2011_la,space_vacant_2011_la_pct,all_households_2001,no_children_2001,dependent_children_2001,nondependent_children_2001,no_children_2001_pct,dependent_children_2001_pct,nondependent_children_2001_pct,all_households_2011,no_children_2011,dependent_children_2011,nondependent_children_2011,no_children_2011_pct,dependent_children_2011_pct,nondependent_children_2011_pct,all_households_2001_la,no_children_2001_la,dependent_children_2001_la,nondependent_children_2001_la,no_children_2001_la_pct,dependent_children_2001_la_pct,nondependent_children_2001_la_pct,all_households_2011_la,no_children_2011_la,dependent_children_2011_la,nondependent_children_2011_la,no_children_2011_la_pct,dependent_children_2011_la_pct,nondependent_children_2011_la_pct,economically_inactive_2001,retired_2001,student_2001,retired_2001_pct,student_2001_pct,economically_inactive_2011,retired_2011,student_2011,retired_2011_pct,student_2011_pct,economically_inactive_2001_la,retired_2001_la,student_2001_la,retired_2001_la_pct,student_2001_la_pct,economically_inactive_2011_la,retired_2011_la,student_2011_la,retired_2011_la_pct,student_2011_la_pct,residents_all_2011,migrants_2011,migrants_2011_pct,residents_all_2001_la,migrants_2001_la,migrants_2001_la_pct,residents_all_2011_la,migrants_2011_la,migrants_2011_la_pct,residential_sale_2001,residential_sale_2011,newlybuilt_sale_2001,newlybuilt_sale_2011,newlybuilt_sale_2001_pct,newlybuilt_sale_2011_pct,residential_sale_2001_la,residential__sale_2011_la,newlybuilt_sale_2001_la,newlybuilt_sale_2011_la,newlybuilt_sale_2001_la_pct,newlybuilt_sale_2011_la_pct,tenure_all_2001,owned_2001,rented_2001,owned_2001_pct,rented_2001_pct,tenure_all_2011,owned_2011,rented_2011,owned_2011_pct,rented_2011_pct,tenure_all_2001_la,owned_2001_la,rented_2001_la,owned_2001_la_pct,rented_2001_la_pct,tenure_all_2011_la,owned_2011_la,rented_2011_la,owned_2011_la_pct,rented_2011_la_pct
1206,E02006840,Torbay 019,E06000027,Torbay,E12000009,South West,E02003160,Torbay 007,M,84500.0,180000,82500,160000,96500,185000,14913.78,11300,15397.0,12777,16958,7807,1841,0.235814,7523,2319.0,0.308255,90852,19026,0.209418,94000,24528,0.260936,3534458,931080,0.263429,3856715,1229068,0.318683,7807,1183.0,0.151531,8667,2163.0,0.249567,90852,12286,0.135231,109290,22564,0.206460,3534458,665869,0.188394,4359257,1193337,0.273748,4744,141,0.029722,4806,305,0.063462,60479,3059,0.050580,64370,5360,0.083269,4601,827.0,1245.0,361.0,0.179744,0.270593,0.078461,4501,816.0,1162.0,409.0,0.181293,0.258165,0.090869,57420,10011.0,14158.0,4374.0,0.174347,0.246569,0.076176,59010,10580.0,13192.0,4850.0,0.179292,0.223555,0.082189,2615,1275,233,0.487572,0.089101,2350,1362,269,0.579574,0.114468,33322.0,16321.0,2372.0,0.489797,0.071184,32205.0,18416.0,3032.0,0.571837,0.094147,10636,851,0.080011,129706,6164,0.047523,130959.0,4938.0,0.037706,303,143,4,8,0.013201,0.055944,4417,1977,272,146,0.061580,0.073849,4603,3589.0,878.0,0.779709,0.190745,4501,3367.0,1089.0,0.748056,0.241946,57420.0,41907.0,13403.0,0.729833,0.233420,59010,39424.0,18458.0,0.668090,0.312794
1207,E02006924,Redbridge 035,E09000026,Redbridge,E12000007,London,E02000771,Redbridge 021,M,165000.0,325000,138500,250000,155000,292688,14867.94,13804,17550.0,16119,22030,8643,2799,0.323846,9356,2955.0,0.315840,171300,53108,0.310029,199544,65964,0.330574,5300332,1818255,0.343045,6117482,2218721,0.362685,8643,2575.0,0.297929,10157,3781.0,0.372256,171300,40811,0.238243,216112,73299,0.339171,5300332,1642467,0.309880,6549173,2470225,0.377181,4213,119,0.028246,4121,101,0.024509,94174,1886,0.020027,101575,2470,0.024317,4094,477.0,1103.0,532.0,0.116512,0.269419,0.129946,4020,371.0,1111.0,562.0,0.092289,0.276368,0.139801,92288,12434.0,28403.0,10352.0,0.134730,0.307765,0.112171,99105,11804.0,31272.0,11409.0,0.119106,0.315544,0.115120,3061,912,712,0.297942,0.232604,3235,951,944,0.293972,0.291808,58007.0,19389.0,11009.0,0.334253,0.189787,61768.0,19026.0,16199.0,0.308024,0.262256,12780,963,0.075352,238635,11993,0.050257,278970.0,14898.0,0.053404,180,92,0,0,0.000000,0.000000,5780,2539,367,80,0.063495,0.031508,4094,3155.0,831.0,0.770640,0.202980,4020,2748.0,1220.0,0.683582,0.303483,92288.0,69008.0,20480.0,0.747746,0.221914,99105,62983.0,33946.0,0.635518,0.342526
1208,E02006925,Redbridge 036,E09000026,Redbridge,E12000007,London,E02000761,Redbridge 011,M,185000.0,326750,138500,250000,155000,292688,16547.20,13804,17550.0,16119,22030,8554,2674,0.312602,9417,3208.0,0.340661,171300,53108,0.310029,199544,65964,0.330574,5300332,1818255,0.343045,6117482,2218721,0.362685,8554,2046.0,0.239186,10341,3521.0,0.340489,171300,40811,0.238243,216112,73299,0.339171,5300332,1642467,0.309880,6549173,2470225,0.377181,4190,54,0.012888,4181,79,0.018895,94174,1886,0.020027,101575,2470,0.024317,4139,506.0,1337.0,657.0,0.122252,0.323025,0.158734,4102,362.0,1356.0,657.0,0.088250,0.330570,0.160166,92288,12434.0,28403.0,10352.0,0.134730,0.307765,0.112171,99105,11804.0,31272.0,11409.0,0.119106,0.315544,0.115120,2862,1037,620,0.362334,0.216632,2955,1002,935,0.339086,0.316413,58007.0,19389.0,11009.0,0.334253,0.189787,61768.0,19026.0,16199.0,0.308024,0.262256,13241,858,0.064799,238635,11993,0.050257,278970.0,14898.0,0.053404,202,110,1,0,0.004950,0.000000,5780,2539,367,80,0.063495,0.031508,4136,3601.0,456.0,0.870648,0.110251,4102,3313.0,731.0,0.807655,0.178206,92288.0,69008.0,20480.0,0.747746,0.221914,99105,62983.0,33946.0,0.635518,0.342526
1209,E02006927,Greenwich 034,E09000011,Greenwich,E12000007,London,E02000336,Greenwich 024,M,127500.0,280000,124995,249995,155000,292688,19259.60,15592,19069.0,16119,22030,7992,2363,0.295671,5910,2228.0,0.376988,153795,44042,0.286368,186722,58787,0.314837,5300332,1818255,0.343045,6117482,2218721,0.362685,7992,2103.0,0.263138,6566,2435.0,0.370850,153795,36439,0.236932,199163,66120,0.331989,5300332,1642467,0.309880,6549173,2470225,0.377181,5030,78,0.015507,3449,111,0.032183,95835,3047,0.031794,103827,2782,0.026795,4951,589.0,1375.0,435.0,0.118966,0.277722,0.087861,3338,441.0,894.0,378.0,0.132115,0.267825,0.113241,92788,11786.0,26372.0,8185.0,0.127021,0.284218,0.088212,101045,13402.0,28602.0,9200.0,0.132634,0.283062,0.091049,2939,874,524,0.297380,0.178292,1891,702,408,0.371232,0.215759,52759.0,15903.0,9400.0,0.301427,0.178169,54649.0,15695.0,13957.0,0.287196,0.255394,8315,657,0.079014,214403,11798,0.055027,254557.0,16607.0,0.065239,146,116,0,12,0.000000,0.103448,4839,2570,899,422,0.185782,0.164202,4952,2180.0,2612.0,0.440226,0.527464,3338,1924.0,1352.0,0.576393,0.405033,92788.0,44870.0,44929.0,0.483575,0.484211,101045,43719.0,54666.0,0.432669,0.541006
1210,E02006882,Harrow 033,E09000015,Harrow,E12000007,London,E02000450,Harrow 018,M,182250.0,315000,166000,294500,155000,292688,15160.69,16118,21231.0,16119,22030,9574,2891,0.301964,10757,3228.0,0.300084,150514,52113,0.346234,174751,61481,0.351821,5300332,1818255,0.343045,6117482,2218721,0.362685,9574,2413.0,0.252037,11628,3885.0,0.334107,150514,44297,0.294305,190998,70218,0.367637,5300332,1642467,0.309880,6549173,2470225,0.377181,4334,84,0.019382,4403,61,0.013854,80904,1792,0.022150,86667,2399,0.027681,4250,478.0,1458.0,653.0,0.112471,0.343059,0.153647,4342,461.0,1195.0,825.0,0.106172,0.275219,0.190005,79112,10962.0,23941.0,9294.0,0.138563,0.302622,0.117479,84268,10341.0,24829.0,11412.0,0.122716,0.294643,0.135425,3072,1012,723,0.329427,0.235352,3120,1182,854,0.378846,0.273718,47465.0,16913.0,9474.0,0.356326,0.199600,51444.0,18189.0,13417.0,0.353569,0.260808,14174,982,0.069282,206814,9968,0.048198,239056.0,11786.0,0.049302,168,79,0,0,0.000000,0.000000,4349,2168,205,141,0.047137,0.065037,4250,3528.0,548.0,0.830118,0.128941,4342,3333.0,893.0,0.767619,0.205666,79112.0,58755.0,17113.0,0.742681,0.216314,84268,55001.0,27247.0,0.652691,0.323337

In [49]:
# get a list of the column names of all the columns that contain percentage information
pct_cols = [col for col in swandlondon.columns if 'pct' in col]
print(pct_cols)

['NS-SeC_higher_2001_pct', 'NS-SeC_higher_2011_pct', 'NS-SeC_higher_2001_la_pct', 'NS-SeC_higher_2011_la_pct', 'NS-SeC_higher_2001_region_pct', 'NS-SeC_higher_2011_region_pct', 'qualification_2001_pct', 'qualification_2011_pct', 'qualification_2001_la_pct', 'qualification_2011_la_pct', 'qualification_2001_region_pct', 'qualification_2011_region_pct', 'space_vacant_2001_pct', 'space_vacant_2011_pct', 'space_vacant_2001_la_pct', 'space_vacant_2011_la_pct', 'no_children_2001_pct', 'dependent_children_2001_pct', 'nondependent_children_2001_pct', 'no_children_2011_pct', 'dependent_children_2011_pct', 'nondependent_children_2011_pct', 'no_children_2001_la_pct', 'dependent_children_2001_la_pct', 'nondependent_children_2001_la_pct', 'no_children_2011_la_pct', 'dependent_children_2011_la_pct', 'nondependent_children_2011_la_pct', 'retired_2001_pct', 'student_2001_pct', 'retired_2011_pct', 'student_2011_pct', 'retired_2001_la_pct', 'student_2001_la_pct', 'retired_2011_la_pct', 'student_2011_la_pct', 'migrants_2011_pct', 'migrants_2001_la_pct', 'migrants_2011_la_pct', 'newlybuilt_sale_2001_pct', 'newlybuilt_sale_2011_pct', 'newlybuilt_sale_2001_la_pct', 'newlybuilt_sale_2011_la_pct', 'owned_2001_pct', 'rented_2001_pct', 'owned_2011_pct', 'rented_2011_pct', 'owned_2001_la_pct', 'rented_2001_la_pct', 'owned_2011_la_pct', 'rented_2011_la_pct']

In [50]:
# get a list of the column names of several columns at the front
front_cols=list(swandlondon.iloc[:,0:20].columns)
print(front_cols)

['MSOA11CD', 'MSOA11NM', 'LAD11CD', 'LAD11NM', 'RGN11CD', 'RGN11NM', 'MSOA01CD', 'MSOA01NM', 'CHGIND', 'median_price_2001', 'median_price_2011', 'median_price_2001_la', 'median_price_2011_la', 'median_price_2001_region', 'median_price_2011_region', 'earnings_2011', 'earnings_2001_la', 'earnings_2011_la', 'earnings_2001_region', 'earnings_2011_region']

In [51]:
#get a list of column names to help extract a subdataset contains all the columns that is essential for further analysis
extract_cols=front_cols+pct_cols

In [52]:
swandlondon_key=swandlondon[extract_cols].copy()

In [53]:
swandlondon_key.to_csv('output/swandlondon_key.csv',index=False)

'swandlondon_key' contains all the raw information

In [54]:
swandlondon_key.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1211 entries, 0 to 1210
Data columns (total 71 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   MSOA11CD                           1211 non-null   object
 1   MSOA11NM                           1211 non-null   object
 2   LAD11CD                            1211 non-null   object
 3   LAD11NM                            1211 non-null   object
 4   RGN11CD                            1211 non-null   object
 5   RGN11NM                            1211 non-null   object
 6   MSOA01CD                           1211 non-null   object
 7   MSOA01NM                           1211 non-null   object
 8   CHGIND                             1211 non-null   object
 9   median_price_2001                  1211 non-null   float64
 10  median_price_2011                  1211 non-null   int64
 11  median_price_2001_la               1211 non-null   int64
 12  median_price_2011_la               1211 non-null   int64
 13  median_price_2001_region           1211 non-null   int64
 14  median_price_2011_region           1211 non-null   int64
 15  earnings_2011                      1211 non-null   float64
 16  earnings_2001_la                   1211 non-null   int64
 17  earnings_2011_la                   1211 non-null   float64
 18  earnings_2001_region               1211 non-null   int64
 19  earnings_2011_region               1211 non-null   int64
 20  NS-SeC_higher_2001_pct             1211 non-null   float64
 21  NS-SeC_higher_2011_pct             1211 non-null   float64
 22  NS-SeC_higher_2001_la_pct          1211 non-null   float64
 23  NS-SeC_higher_2011_la_pct          1211 non-null   float64
 24  NS-SeC_higher_2001_region_pct      1211 non-null   float64
 25  NS-SeC_higher_2011_region_pct      1211 non-null   float64
 26  qualification_2001_pct             1211 non-null   float64
 27  qualification_2011_pct             1211 non-null   float64
 28  qualification_2001_la_pct          1211 non-null   float64
 29  qualification_2011_la_pct          1211 non-null   float64
 30  qualification_2001_region_pct      1211 non-null   float64
 31  qualification_2011_region_pct      1211 non-null   float64
 32  space_vacant_2001_pct              1211 non-null   float64
 33  space_vacant_2011_pct              1211 non-null   float64
 34  space_vacant_2001_la_pct           1211 non-null   float64
 35  space_vacant_2011_la_pct           1211 non-null   float64
 36  no_children_2001_pct               1211 non-null   float64
 37  dependent_children_2001_pct        1211 non-null   float64
 38  nondependent_children_2001_pct     1211 non-null   float64
 39  no_children_2011_pct               1211 non-null   float64
 40  dependent_children_2011_pct        1211 non-null   float64
 41  nondependent_children_2011_pct     1211 non-null   float64
 42  no_children_2001_la_pct            1211 non-null   float64
 43  dependent_children_2001_la_pct     1211 non-null   float64
 44  nondependent_children_2001_la_pct  1211 non-null   float64
 45  no_children_2011_la_pct            1211 non-null   float64
 46  dependent_children_2011_la_pct     1211 non-null   float64
 47  nondependent_children_2011_la_pct  1211 non-null   float64
 48  retired_2001_pct                   1211 non-null   float64
 49  student_2001_pct                   1211 non-null   float64
 50  retired_2011_pct                   1211 non-null   float64
 51  student_2011_pct                   1211 non-null   float64
 52  retired_2001_la_pct                1211 non-null   float64
 53  student_2001_la_pct                1211 non-null   float64
 54  retired_2011_la_pct                1211 non-null   float64
 55  student_2011_la_pct                1211 non-null   float64
 56  migrants_2011_pct                  1211 non-null   float64
 57  migrants_2001_la_pct               1211 non-null   float64
 58  migrants_2011_la_pct               1211 non-null   float64
 59  newlybuilt_sale_2001_pct           1211 non-null   float64
 60  newlybuilt_sale_2011_pct           1211 non-null   float64
 61  newlybuilt_sale_2001_la_pct        1211 non-null   float64
 62  newlybuilt_sale_2011_la_pct        1211 non-null   float64
 63  owned_2001_pct                     1211 non-null   float64
 64  rented_2001_pct                    1211 non-null   float64
 65  owned_2011_pct                     1211 non-null   float64
 66  rented_2011_pct                    1211 non-null   float64
 67  owned_2001_la_pct                  1211 non-null   float64
 68  rented_2001_la_pct                 1211 non-null   float64
 69  owned_2011_la_pct                  1211 non-null   float64
 70  rented_2011_la_pct                 1211 non-null   float64
dtypes: float64(54), int64(8), object(9)
memory usage: 671.9+ KB

In [55]:
swandlondon_key['ratio_la_median_price_2001']=(swandlondon_key['median_price_2001']/swandlondon_key['median_price_2001_la'])
swandlondon_key['ratio_la_median_price_2011']=(swandlondon_key['median_price_2011']/swandlondon_key['median_price_2011_la'])
swandlondon_key['ratio_r_median_price_2001']=(swandlondon_key['median_price_2001']/swandlondon_key['median_price_2001_region'])
swandlondon_key['ratio_r_median_price_2011']=(swandlondon_key['median_price_2011']/swandlondon_key['median_price_2011_region'])

swandlondon_key['ratio_la_earnings_2001']=(swandlondon_key['earnings_2001_la']/swandlondon_key['earnings_2001_la'])
swandlondon_key['ratio_la_earnings_2011']=(swandlondon_key['earnings_2011']/swandlondon_key['earnings_2011_la'])
swandlondon_key['ratio_r_earnings_2001']=(swandlondon_key['earnings_2001_la']/swandlondon_key['earnings_2001_region'])
swandlondon_key['ratio_r_earnings_2011']=(swandlondon_key['earnings_2011']/swandlondon_key['earnings_2011_region'])

swandlondon_key['ratio_la_nssec_2001']=(swandlondon_key['NS-SeC_higher_2001_pct']/swandlondon_key['NS-SeC_higher_2001_la_pct'])
swandlondon_key['ratio_la_nssec_2011']=(swandlondon_key['NS-SeC_higher_2011_pct']/swandlondon_key['NS-SeC_higher_2011_la_pct'])
swandlondon_key['ratio_r_nssec_2001']=(swandlondon_key['NS-SeC_higher_2001_pct']/swandlondon_key['NS-SeC_higher_2001_region_pct'])
swandlondon_key['ratio_r_nssec_2011']=(swandlondon_key['NS-SeC_higher_2011_pct']/swandlondon_key['NS-SeC_higher_2011_region_pct'])

swandlondon_key['ratio_la_qualification_2001']=(swandlondon_key['qualification_2001_pct']/swandlondon_key['qualification_2001_la_pct'])
swandlondon_key['ratio_la_qualification_2011']=(swandlondon_key['qualification_2011_pct']/swandlondon_key['qualification_2011_la_pct'])
swandlondon_key['ratio_r_qualification_2001']=(swandlondon_key['qualification_2001_pct']/swandlondon_key['qualification_2001_region_pct'])
swandlondon_key['ratio_r_qualification_2011']=(swandlondon_key['qualification_2011_pct']/swandlondon_key['qualification_2011_region_pct'])

In [56]:
for name in ['space_vacant', 'no_children', 'dependent_children','nondependent_children', 'retired', 'student', 'newlybuilt_sale','owned', 'rented']:
    for ind, row in swandlondon_key.iterrows():
        swandlondon_key.loc[ind,'ratio_la_'+name+'_2001'] = row[name + '_2001_pct']/row[name + '_2001_la_pct']
        swandlondon_key.loc[ind,'ratio_la_'+name+'_2011'] = row[name + '_2011_pct']/row[name + '_2011_la_pct']
        
#code reference: https://www.youtube.com/watch?v=nH1gw-slnOo

In [57]:
swandlondon_key['ratio_la_migrants_2001']=(swandlondon_key['migrants_2001_la_pct']/swandlondon_key['migrants_2001_la_pct'])
swandlondon_key['ratio_la_migrants_2011']=(swandlondon_key['migrants_2011_pct']/swandlondon_key['migrants_2011_la_pct'])

In [58]:
swandlondon_key.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1211 entries, 0 to 1210
Data columns (total 107 columns):
 #   Column                               Dtype
---  ------                               -----
 0   MSOA11CD                             object
 1   MSOA11NM                             object
 2   LAD11CD                              object
 3   LAD11NM                              object
 4   RGN11CD                              object
 5   RGN11NM                              object
 6   MSOA01CD                             object
 7   MSOA01NM                             object
 8   CHGIND                               object
 9   median_price_2001                    float64
 10  median_price_2011                    int64
 11  median_price_2001_la                 int64
 12  median_price_2011_la                 int64
 13  median_price_2001_region             int64
 14  median_price_2011_region             int64
 15  earnings_2011                        float64
 16  earnings_2001_la                     int64
 17  earnings_2011_la                     float64
 18  earnings_2001_region                 int64
 19  earnings_2011_region                 int64
 20  NS-SeC_higher_2001_pct               float64
 21  NS-SeC_higher_2011_pct               float64
 22  NS-SeC_higher_2001_la_pct            float64
 23  NS-SeC_higher_2011_la_pct            float64
 24  NS-SeC_higher_2001_region_pct        float64
 25  NS-SeC_higher_2011_region_pct        float64
 26  qualification_2001_pct               float64
 27  qualification_2011_pct               float64
 28  qualification_2001_la_pct            float64
 29  qualification_2011_la_pct            float64
 30  qualification_2001_region_pct        float64
 31  qualification_2011_region_pct        float64
 32  space_vacant_2001_pct                float64
 33  space_vacant_2011_pct                float64
 34  space_vacant_2001_la_pct             float64
 35  space_vacant_2011_la_pct             float64
 36  no_children_2001_pct                 float64
 37  dependent_children_2001_pct          float64
 38  nondependent_children_2001_pct       float64
 39  no_children_2011_pct                 float64
 40  dependent_children_2011_pct          float64
 41  nondependent_children_2011_pct       float64
 42  no_children_2001_la_pct              float64
 43  dependent_children_2001_la_pct       float64
 44  nondependent_children_2001_la_pct    float64
 45  no_children_2011_la_pct              float64
 46  dependent_children_2011_la_pct       float64
 47  nondependent_children_2011_la_pct    float64
 48  retired_2001_pct                     float64
 49  student_2001_pct                     float64
 50  retired_2011_pct                     float64
 51  student_2011_pct                     float64
 52  retired_2001_la_pct                  float64
 53  student_2001_la_pct                  float64
 54  retired_2011_la_pct                  float64
 55  student_2011_la_pct                  float64
 56  migrants_2011_pct                    float64
 57  migrants_2001_la_pct                 float64
 58  migrants_2011_la_pct                 float64
 59  newlybuilt_sale_2001_pct             float64
 60  newlybuilt_sale_2011_pct             float64
 61  newlybuilt_sale_2001_la_pct          float64
 62  newlybuilt_sale_2011_la_pct          float64
 63  owned_2001_pct                       float64
 64  rented_2001_pct                      float64
 65  owned_2011_pct                       float64
 66  rented_2011_pct                      float64
 67  owned_2001_la_pct                    float64
 68  rented_2001_la_pct                   float64
 69  owned_2011_la_pct                    float64
 70  rented_2011_la_pct                   float64
 71  ratio_la_median_price_2001           float64
 72  ratio_la_median_price_2011           float64
 73  ratio_r_median_price_2001            float64
 74  ratio_r_median_price_2011            float64
 75  ratio_la_earnings_2001               float64
 76  ratio_la_earnings_2011               float64
 77  ratio_r_earnings_2001                float64
 78  ratio_r_earnings_2011                float64
 79  ratio_la_nssec_2001                  float64
 80  ratio_la_nssec_2011                  float64
 81  ratio_r_nssec_2001                   float64
 82  ratio_r_nssec_2011                   float64
 83  ratio_la_qualification_2001          float64
 84  ratio_la_qualification_2011          float64
 85  ratio_r_qualification_2001           float64
 86  ratio_r_qualification_2011           float64
 87  ratio_la_space_vacant_2001           float64
 88  ratio_la_space_vacant_2011           float64
 89  ratio_la_no_children_2001            float64
 90  ratio_la_no_children_2011            float64
 91  ratio_la_dependent_children_2001     float64
 92  ratio_la_dependent_children_2011     float64
 93  ratio_la_nondependent_children_2001  float64
 94  ratio_la_nondependent_children_2011  float64
 95  ratio_la_retired_2001                float64
 96  ratio_la_retired_2011                float64
 97  ratio_la_student_2001                float64
 98  ratio_la_student_2011                float64
 99  ratio_la_newlybuilt_sale_2001        float64
 100 ratio_la_newlybuilt_sale_2011        float64
 101 ratio_la_owned_2001                  float64
 102 ratio_la_owned_2011                  float64
 103 ratio_la_rented_2001                 float64
 104 ratio_la_rented_2011                 float64
 105 ratio_la_migrants_2001               float64
 106 ratio_la_migrants_2011               float64
dtypes: float64(90), int64(8), object(9)
memory usage: 1012.4+ KB

In [59]:
# get a list of the column names of all the columns that contain ratio information
ratio_cols = [col for col in swandlondon_key.columns if 'ratio' in col]

# get a list of the column names of several columns at the front
head_cols=list(swandlondon_key.iloc[:,0:9].columns)

#get a list of column names to help extract a subdataset contains all the columns that is essential for duther analysis
extract_cols2=head_cols+ratio_cols

print(extract_cols2)

['MSOA11CD', 'MSOA11NM', 'LAD11CD', 'LAD11NM', 'RGN11CD', 'RGN11NM', 'MSOA01CD', 'MSOA01NM', 'CHGIND', 'ratio_la_median_price_2001', 'ratio_la_median_price_2011', 'ratio_r_median_price_2001', 'ratio_r_median_price_2011', 'ratio_la_earnings_2001', 'ratio_la_earnings_2011', 'ratio_r_earnings_2001', 'ratio_r_earnings_2011', 'ratio_la_nssec_2001', 'ratio_la_nssec_2011', 'ratio_r_nssec_2001', 'ratio_r_nssec_2011', 'ratio_la_qualification_2001', 'ratio_la_qualification_2011', 'ratio_r_qualification_2001', 'ratio_r_qualification_2011', 'ratio_la_space_vacant_2001', 'ratio_la_space_vacant_2011', 'ratio_la_no_children_2001', 'ratio_la_no_children_2011', 'ratio_la_dependent_children_2001', 'ratio_la_dependent_children_2011', 'ratio_la_nondependent_children_2001', 'ratio_la_nondependent_children_2011', 'ratio_la_retired_2001', 'ratio_la_retired_2011', 'ratio_la_student_2001', 'ratio_la_student_2011', 'ratio_la_newlybuilt_sale_2001', 'ratio_la_newlybuilt_sale_2011', 'ratio_la_owned_2001', 'ratio_la_owned_2011', 'ratio_la_rented_2001', 'ratio_la_rented_2011', 'ratio_la_migrants_2001', 'ratio_la_migrants_2011']

In [60]:
swandlondon_core=swandlondon_key[extract_cols2].copy()

'swandlondon_core'only contains all the 'ratio variables'

In [61]:
swandlondon_core.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1211 entries, 0 to 1210
Data columns (total 45 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   MSOA11CD                             1211 non-null   object
 1   MSOA11NM                             1211 non-null   object
 2   LAD11CD                              1211 non-null   object
 3   LAD11NM                              1211 non-null   object
 4   RGN11CD                              1211 non-null   object
 5   RGN11NM                              1211 non-null   object
 6   MSOA01CD                             1211 non-null   object
 7   MSOA01NM                             1211 non-null   object
 8   CHGIND                               1211 non-null   object
 9   ratio_la_median_price_2001           1211 non-null   float64
 10  ratio_la_median_price_2011           1211 non-null   float64
 11  ratio_r_median_price_2001            1211 non-null   float64
 12  ratio_r_median_price_2011            1211 non-null   float64
 13  ratio_la_earnings_2001               1211 non-null   float64
 14  ratio_la_earnings_2011               1211 non-null   float64
 15  ratio_r_earnings_2001                1211 non-null   float64
 16  ratio_r_earnings_2011                1211 non-null   float64
 17  ratio_la_nssec_2001                  1211 non-null   float64
 18  ratio_la_nssec_2011                  1211 non-null   float64
 19  ratio_r_nssec_2001                   1211 non-null   float64
 20  ratio_r_nssec_2011                   1211 non-null   float64
 21  ratio_la_qualification_2001          1211 non-null   float64
 22  ratio_la_qualification_2011          1211 non-null   float64
 23  ratio_r_qualification_2001           1211 non-null   float64
 24  ratio_r_qualification_2011           1211 non-null   float64
 25  ratio_la_space_vacant_2001           1211 non-null   float64
 26  ratio_la_space_vacant_2011           1211 non-null   float64
 27  ratio_la_no_children_2001            1211 non-null   float64
 28  ratio_la_no_children_2011            1211 non-null   float64
 29  ratio_la_dependent_children_2001     1211 non-null   float64
 30  ratio_la_dependent_children_2011     1211 non-null   float64
 31  ratio_la_nondependent_children_2001  1211 non-null   float64
 32  ratio_la_nondependent_children_2011  1211 non-null   float64
 33  ratio_la_retired_2001                1211 non-null   float64
 34  ratio_la_retired_2011                1211 non-null   float64
 35  ratio_la_student_2001                1211 non-null   float64
 36  ratio_la_student_2011                1211 non-null   float64
 37  ratio_la_newlybuilt_sale_2001        1211 non-null   float64
 38  ratio_la_newlybuilt_sale_2011        1211 non-null   float64
 39  ratio_la_owned_2001                  1211 non-null   float64
 40  ratio_la_owned_2011                  1211 non-null   float64
 41  ratio_la_rented_2001                 1211 non-null   float64
 42  ratio_la_rented_2011                 1211 non-null   float64
 43  ratio_la_migrants_2001               1211 non-null   float64
 44  ratio_la_migrants_2011               1211 non-null   float64
dtypes: float64(36), object(9)
memory usage: 425.9+ KB

In [62]:
swandlondon_core.to_csv('output/swandlondon_core.csv',index=False)